### ISSUE TITLE
[OLImageSourceArray _objectAtIndex:] CGImageSourceCreateImageAtIndex crash randomly

### ISSUE THREAD

**Issue by liunice** [dtorres/OLImageView#62] opened 2015-07-19 15:43 UTC
I can't reproduce this crash. FYI, I'm using release version 1.5.

SIGTRAP
0
0	CoreFoundation	0x00000001824b1cec	____forwarding___
1	CoreFoundation	0x00000001823b6c1c	_CF_forwarding_prep_0 + 80
2	CoreFoundation	0x000000018238d378	CFRelease + 516
3	CoreFoundation	0x00000001823ad218	CFArraySetValueAtIndex + 480
4	ImageIO	0x0000000183666c44	_makeImagePlus
5	ImageIO	0x0000000183666248	CGImageSourceCreateImageAtIndex + 176
6	WeiboFun	0x0000000100282328	-[OLImageSourceArray _objectAtIndex:] (OLImage.m:457)
7	WeiboFun	0x00000001002821c8	-[OLImageSourceArray objectAtIndex:] (OLImage.m:445)
8	WeiboFun	0x0000000100205948	-[OLImageView displayLayer:] (OLImageView.m:180)
9	QuartzCore	0x00000001865caf74	CA::Layer::display()
10	QuartzCore	0x00000001865ac75c	CA::Layer::display_if_needed(CA::Transaction*)
11	QuartzCore	0x00000001865ac414	CA::Layer::layout_and_display_if_needed(CA::Transaction*)
12	QuartzCore	0x00000001865abc08	CA::Context::commit_transaction(CA::Transaction*)
13	QuartzCore	0x00000001865ab98c	CA::Transaction::commit()
14	QuartzCore	0x00000001866011d8	CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long)
15	IOKit	0x00000001835f98d0	IODispatchCalloutFromCFMessage + 376
16	CoreFoundation	0x0000000182450ce0	___CFMachPortPerform
17	CoreFoundation	0x00000001824658fc	___CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
18	CoreFoundation	0x000000018246585c	___CFRunLoopDoSource1
19	CoreFoundation	0x00000001824637dc	___CFRunLoopRun
20	CoreFoundation	0x00000001823911f4	CFRunLoopRunSpecific + 392
21	GraphicsServices	0x000000018b51f5a4	GSEventRunModal + 164
22	UIKit	0x0000000186cc2784	UIApplicationMain + 1484
23	WeiboFun	0x00000001000b0144	main (main.m:14)
24	libdyld.dylib	0x0000000193262a08	_start

**Comment by dtorres** [comment] 2015-07-19 22:09
Judging by the stack this might be because of a malformed image, If you can't create a reproducible case I can't do much for you. 

Please do comment when you have a reproducible case, closing for now.

**Closed by dtorres** 2015-07-19 22:09 UTC
